Models/ErrorViewModel.cs
namespace BoardWepApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserInfo.cs
namespace BoardWepApp.Models
{
    public class UserInfo
    {

        private DBService context;
        public string id { get; set; } 
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public int phone { get; set; }
      


    }
}

Controllers/AccountController.cs
using BoardWepApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BoardWepApp.Controllers
{
    public class AccountController : Controller
    {

        //회원가입 View
        public IActionResult SignUp()
        {
            return View();
        }

        //회원 정보수정 View
        public IActionResult ModifyInfo(string id)
        {
            DBService context = HttpContext.RequestServices.GetService(typeof(DBService)) as DBService;
            UserInfo user = context.GetUserInfo(id);
            return View(user);
        }

        //로그인 View
        public IActionResult Login()
        {
            return View();
        }


        //아이디 중복체크
        public int IdCheck(UserInfo userInfo)
        {

            DBService context = HttpContext.RequestServices.GetService(typeof(DBService)) as DBService;
            int count = context.IdCheck(userInfo.id);
            
            return count;
        }
        //회원가입클릭시 회원정보 등록
        public void UserRegist(UserInfo userInfo)
        {
            DBService context = HttpContext.RequestServices.GetService(typeof(DBService)) as DBService;
            context.UserRegist(userInfo);

            //로그인 창으로이동
            Response.Redirect(String.Format("Login"));

        }

        public string LoginTry(UserInfo userInfo)
        {
           
            DBService context = HttpContext.RequestServices.GetService(typeof(DBService)) as DBService;
            string result = context.LoginTry(userInfo);


            if (result.Equals("Success"))
            {   
                Response.Redirect(String.Format("/Board"));
                return "";
            }
            else return result;
        }

    }
}

Controllers/BoardController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace BoardWepApp.Controllers
{
    public class BoardController : Controller
    {

        //GET : /Board/
        public IActionResult Index()
        {
            return View();
        }

        //GET: /Board/Welcome/
        public string Welcome(string name,int age =1) {


            return name+"님반갑습니다 나이는 "+age+"세입니다";
                   
         }
    }
}

Controllers/HomeController.cs
using BoardWepApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BoardWepApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Board/Index.cshtml
<title>@ViewData["Title"]- 게시글 목록</title>
<h2>게시글 목록</h2>

<p>게시판 인덱스</p>
<a href='/Account/Login' class='btn-primary' >로그인하기</a>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TL Community</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BoardWepApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Board" asp-action="Index">게시판</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role ="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - 게시판 앱 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>